### ISSUE TITLE
tempfile: command not found

### ISSUE THREAD

**Issue by manchikr** [dverite/postgresql-functions#3]
1. I am getting sh: tempfile: command not found
2. goes to vi and stays, I need to quit vi after that
3. it shows column and its type. instead of data

Please let me know how I can setup query for data. Thanks in advance

**Comment by dverite** [comment]
What is your operating system? In Debian for instance tempfile is provided by the debian-utils package.

Does it work if you replace tempfile with **mktemp** ?

**Comment by manchikr** [comment]
Hi Daniel,

Thanks for quick response.

I am on MacOS, either mktemp did not work

Thank you,
Ramesh
CDK Global | Platform Services


From: Daniel Vérité ***@***.***>
Date: Thursday, November 17, 2022 at 3:30 PM
To: dverite/postgresql-functions ***@***.***>
Cc: Manchikanti, Ramesh ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [dverite/postgresql-functions] tempfile: command not found (Issue #3)

Caution: External email - Please use caution opening links and attachments from external senders

What is your operating system? In Debian for instance tempfile is provided by the debian-utils package.

Does it work if you replace tempfile with mktemp ?

**Comment by dverite** [comment]
I'm afraid I don't have access to a MacOS machine to test, but  it looks like mktemp does exist there, since people online are discussing how it differs from some other Unix systems, but not that it doesn't exist. For instance
https://unix.stackexchange.com/questions/555058/mktemp-on-macos-not-honouring-tmpdir

**Comment by dverite** [comment]
Committed the tempfile->mktemp substitution (4440fdaf2)
