### ISSUE TITLE
Add installation notes to README

### ISSUE THREAD

**Issue by bernd-wechner** [dverite/postgresql-functions#4]
Perhaps I'm unforgivably naive? Or blind? I just read the README for the global_search function, and **love** this. Just what I want. And I see there's a .sql file, great, and I use pgadmin a lot, and work with postgres a fair bit, but still feel rather clueless as to how to make this function available ... so that I can `SELECT * FROM global_search('Foo');`. 

Now yes, I know, I searched on-line I did some reading, and yep, just ran the SQL and can see the function in pgadmin in my database and selected from it! It all worked. But I hope it's not deemed presumptuous, naive, or stupid of me my postgresql pros who assemble such functions, but yep a short note for orientation on how to make the function available to you (aka install it) would to my mind be useful and welcome. And yes, you can validly argue that this is presumed knowledge and close this and ignore it, or take the feedback as it stands that yep, even a moderately experienced postgres user has a moment when they first encounter "functions" I guess.

**Comment by dverite** [comment]
Thanks for your feedback! You're right that in this repository of code with its short READMEs, how to create the functions is presumed to be known. But I'll take your point that it's not necessarily true for all users and will add a few explanations.
